ReddiMiras/Models/DataContext/ReddiMirasDBContext.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using ReddiMiras.Models.Model;

namespace ReddiMiras.Models.DataContext
{
    public class ReddiMirasDBContext:DbContext
    {
        public ReddiMirasDBContext()
        {
        }

        public ReddiMirasDBContext(DbContextOptions<ReddiMirasDBContext> options)
            : base(options)
        {

        }

        public DbSet<Users> Users { get; set; }
    }
}

ReddiMiras/Models/Model/Users.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ReddiMiras.Models.Model
{
    public class Users
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string Email { get; set; }
        [Required(ErrorMessage = "Şifreniz en az 7 karakter içermelidir.")]
        [StringLength(70, MinimumLength = 7)]
        public string Password { get; set; }

        public string Name { get; set; }
        public string Surname { get; set; }
        public string ActivationCode { get; set; }
        [Required(ErrorMessage = "TC Kimlik Numarası 11 karakterli olmalıdır.")]
        [StringLength(11, MinimumLength = 11)]
        public string TCNo { get; set; }
        public string CompanyName { get; set; }
        public string BillingAddress { get; set; }
        public string TaxNumber { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public DateTime BirthDate { get; set; }
        public string DegreeOfProximity { get; set; }
        public string BasisNo { get; set; }
        public string Decision { get; set; }
        public string NameSurname { get; set; }
        public string TaxOffice { get; set; }
        public string DeathName { get; set; }
        public string DeathSurname { get; set; }
        public string DeathTCNo { get; set; }
        public DateTime DeathBirthDate { get; set; }
        public string File { get; set; }
    }
}

ReddiMiras/Controllers/AllQueryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace ReddiMiras.Controllers
{
    public class AllQueryController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

ReddiMiras/Controllers/CreditLoadController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace ReddiMiras.Controllers
{
    public class CreditLoadController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

ReddiMiras/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace ReddiMiras.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult CitizenProfile()
        {
            return View();
        }

        public IActionResult Sss()
        {
            return View();
        }

        public IActionResult SiteGoal()
        {
            return View();
        }

        public IActionResult WhatisRejedtion()
        {
            return View();
        }

        public IActionResult Kvkk()
        {
            return View();
        }

        public IActionResult UserAgreement()
        {
            return View();
        }
    }
}

ReddiMiras/Controllers/MyAccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace ReddiMiras.Controllers
{
    public class MyAccountController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

ReddiMiras/Controllers/PastQueriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace ReddiMiras.Controllers
{
    public class PastQueriesController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

ReddiMiras/Controllers/PastQueryDetailController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace ReddiMiras.Controllers
{
    public class PastQueryDetailController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

ReddiMiras/Controllers/QueryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace ReddiMiras.Controllers
{
    public class QueryController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

ReddiMiras/ViewComponents/CitizenViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ReddiMiras.ViewComponents
{
    public class CitizenViewComponent:ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View();
        }
    }
}

ReddiMiras/ViewComponents/FooterViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ReddiMiras.ViewComponents
{
    public class FooterViewComponent:ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View();
        }
    }
}

ReddiMiras/ViewComponents/HeaderViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ReddiMiras.ViewComponents
{
    public class HeaderViewComponent:ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View();
        }
    }
}

ReddiMiras/ViewComponents/HeaderinPageViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ReddiMiras.ViewComponents
{
    public class HeaderinPageViewComponent:ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View();
        }
    }
}

ReddiMiras/ViewComponents/InquiryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ReddiMiras.ViewComponents
{
    public class InquiryViewComponent:ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View();
        }
    }
}

ReddiMiras/ViewComponents/LeftNavViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ReddiMiras.ViewComponents
{
    public class LeftNavViewComponent:ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View();
        }
    }
}

ReddiMiras/Views/AllQuery/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_QueryPage.cshtml";
}

<style>

    body {
        background-image: none !important;
    }

    footer {
        bottom: auto;
    }

    .detail-content {
        height: auto;
        min-height: 700px;
    }
</style>
<div class="breadcrumb">
    <div class="container">
        <div class="text-right">
            <h1>Türkoğlu Avukatlık Bürosu</h1>
            <h2>TC SORGULAMA EKRANI</h2>

            <h3>Hesabınızda</h3>
            <p>55 Kontür / 55 Sorgulama Bulunmaktadır.</p>
        </div>
    </div>
</div>

<div class="container detail-content">
    <div class="row">
        @await Component.InvokeAsync("LeftNav")
        <div class="col-lg-8 col-md-12">
            <h1>Tümünü Sorgula</h1>
            <div class="row">
                <div class="col-6">
                    <p class="card-text">Elindeki TC. Listesini Yükle</p>
                    <input type="file" class="form-control-file" id="exampleFormControlFile1">
                </div>
                <div class="col-6">
                    <p class="card-text">Örnek excel dökümanını indirebilirsiniz.</p>
                    <a href="#" class="btn btn-success">İndir</a>
                </div>
            </div>

            <hr>
            <p> Excel listeniz içerisinden 7 adet sorgulanacak TC bulunmuştur. </p>
            <div class="alert alert-success" role="alert">
                4 Adet TC. nin karşılığı aşağıda listelenmiştir.
            </div>


            <div class="responsive-table">
                <table class="table table-striped table-dark">
                    <thead>
                        <tr>
                            <th scope="col">TC.</th>
                            <th scope="col">Doğum T.</th>
                            <th scope="col">Tel</th>
                            <th scope="col">Esas No</th>
                            <th scope="col">Karar No</th>
                            <th scope="col">Ad / Soyad</th>
                            <th scope="col">Detay</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <th scope="row">34798612886</th>
                            <td>05322001146</td>
                            <td>39204</td>
                            <td>234242</td>
                            <td>Süha Uzun</td>
                            <td>İndir</td>
                            <td><a href="/gecmissorgulardetay">Detay</a></td>
                        </tr>
                        <tr>
                            <th scope="row">34798612886</th>
                            <td>05322001146</td>
                            <td>39204</td>
                            <td>234242</td>
                            <td>Süha Uzun</td>
                            <td>İndir</td>
                            <td><a href="/gecmissorgulardetay">Detay</a></td>
                        </tr>
                        <tr>
                            <th scope="row">34798612886</th>
                            <td>05322001146</td>
                            <td>39204</td>
                            <td>234242</td>
                            <td>Süha Uzun</td>
                            <td>İndir</td>
                            <td><a href="/gecmissorgulardetay">Detay</a></td>
                        </tr>
                        <tr>
                            <th scope="row">34798612886</th>
                            <td>05322001146</td>
                            <td>39204</td>
                            <td>234242</td>
                            <td>Süha Uzun</td>
                            <td>İndir</td>
                            <td><a href="/gecmissorgulardetay">Detay</a></td>
                        </tr>

                    </tbody>
                </table>
            </div>
            <div class="alert alert-danger" role="alert">
                3 adet TC. bulunamamıştır. Bulunamayan TC. lerin listesini görmek için tıkla.
            </div>

            <div class="responsive-table">
                <table class="table table-striped table-dark">
                    <thead>
                        <tr>
                            <th scope="col">TC.</th>
                            <th scope="col">Durum</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <th scope="row">34798612886</th>
                            <td>Bulunamadı</td>
                        </tr>
                        <tr>
                            <th scope="row">34798612886</th>
                            <td>Bulunamadı</td>
                        </tr>
                        <tr>
                            <th scope="row">34798612886</th>
                            <td>Bulunamadı</td>
                        </tr>
                    </tbody>
                </table>

            </div>


        </div>
    </div>
</div>

<div class="clearfix">...</div>

@await Component.InvokeAsync("Footer")
@await Component.InvokeAsync("Inquiry")
@await Component.InvokeAsync("Citizen")

ReddiMiras/Views/CreditLoad/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_QueryPage.cshtml";
}

<style>

    body {
        background-image: none !important;
    }

    footer {
        bottom: auto;
    }

    .detail-content {
        height: auto;
        min-height: 700px;
    }
</style>
<div class="breadcrumb">
    <div class="container">
        <div class="text-right">
            <h1>Türkoğlu Avukatlık Bürosu</h1>
            <h2>TC SORGULAMA EKRANI</h2>

            <h3>Hesabınızda</h3>
            <p>55 Kontür / 55 Sorgulama Bulunmaktadır.</p>
        </div>
    </div>
</div>

<div class="container detail-content">
    <div class="row">
        @await Component.InvokeAsync("LeftNav")
        <div class="col-lg-8 col-md-12">
            <h1>Kontür Yükle</h1>
            <form>
                <div class="form-group">
                    <label for="formControlRange"></label>
                    <input type="range" class="form-control-range" min="1" max="100" value="50" class="slider" id="myRange">
                </div>

            </form>
            <!-- credit card info-->
            <div class="row">

                <div class="col-lg-6 col-md-12">
                    <div class="card ">
                        <div class="card-body">
                            <p><strong>Sipariş Özetiniz</strong></p>
                            <hr>
                            <div class="alert alert-primary" role="alert">
                                <span id="demo2"></span> Kontür : <span id="demo3"></span> Sorgu demektir
                            </div>
                            <p>KDV Tutarı (%18)</p>
                            <p> Ödenecek Tutar </p>
                            <hr>
                            <h2><span id="demo"></span> TL</h2>



                        </div>
                    </div>

                </div>

                <div id="nav-tab-card" class="col-lg-6 col-md-12">
                    <p class="alert alert-danger">Bir Sorun Oluştu</p>
                    <form role="form">
                        <div class="form-group">
                            <label for="username">Kart Üzerindeki Ad Soyad</label>
                            <input type="text" name="username" placeholder="Jason Doe" required class="form-control">
                        </div>
                        <div class="form-group">
                            <label for="cardNumber">Kart Numaranız</label>
                            <div class="input-group">
                                <input type="text" name="cardNumber" placeholder="Your card number" class="form-control" required>
                                <div class="input-group-append">
                                    <span class="input-group-text text-muted">
                                        <i class="fa fa-cc-visa mx-1"></i>
                                        <i class="fa fa-cc-amex mx-1"></i>
                                        <i class="fa fa-cc-mastercard mx-1"></i>
                                    </span>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-8">
                                <div class="form-group">
                                    <label><span class="hidden-xs">Son Kullanım Tarihi</span></label>
                                    <div class="input-group">
                                        <input type="number" placeholder="MM" name="" class="form-control" required>
                                        <input type="number" placeholder="YY" name="" class="form-control" required>
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-4">
                                <div class="form-group mb-4">
                                    <label data-toggle="tooltip" title="Kartınızın arkasında yer alan 3 haneli numarayı giriniz.">
                                        CVV
                                        <i class="fa fa-question-circle"></i>
                                    </label>
                                    <input type="text" required class="form-control">
                                </div>
                            </div>



                        </div>

                        <div class="form-group form-check">
                            <input type="checkbox" class="form-check-input" id="exampleCheck1">
                            <label class="form-check-label" for="exampleCheck1">3D Secure İle Ödeme <i class="fa fa-question-circle" data-toggle="tooltip" data-placement="right" title="Güvenliğiniz için sms ile doğrulama gerekmektedir."></i></label>
                        </div>
                        <button type="button" class="subscribe btn btn-primary btn-block" data-toggle="modal" data-target="#basariliislem"> Satın Al  </button>
                    </form>
                </div>
            </div>
            <!--Credit End-->





        </div>
    </div>
</div>

<div class="clearfix">...</div>


<!-- Başarılı İşlem Modalı -->
<div class="modal fade paymentmethod" id="basariliislem" tabindex="-1" role="dialog" aria-labelledby="basariliislemLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header text-center">
                <h5 class="modal-title " id="basariliislemLabel">İşleminiz Başarıyla Gerçekleştirilmiştir.</h5>

            </div>
            <div class="modal-body text-center">
                <i class="fa fa-check-circle succses-circle"></i>
                <!-- <i class="fa fa-check-circle danger-circle"></i> -->
            </div>

        </div>
    </div>
</div>
<!-- Başarılı İşlem Modalı End -->


<script>
    var slider = document.getElementById("myRange");
    var output = document.getElementById("demo");
    var output2 = document.getElementById("demo2");
    var output3 = document.getElementById("demo3");
    output.innerHTML = slider.value;
    output2.innerHTML = slider.value;
    output3.innerHTML = slider.value;

    //output3.innerHTML = (slider.value)/2;

    slider.oninput = function () {
        output.innerHTML = this.value;
        output2.innerHTML = this.value;
        output3.innerHTML = this.value;
        //  output3.innerHTML = ((this.value)/2).toFixed();
    };</script>

@await Component.InvokeAsync("Footer")
@await Component.InvokeAsync("Inquiry")
@await Component.InvokeAsync("Citizen")

ReddiMiras/Views/Home/CitizenProfile.cshtml
@{
    ViewData["Title"] = "CitizenProfile";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>

    body {
        background-image: none !important;
    }

    footer {
        bottom: auto;
    }

    .detail-content {
        height: auto;
        min-height: 700px;
    }
</style>
<div class="breadcrumb">
    <div class="container">

    </div>
</div>

<div class="container detail-content">



    <h1>Eklenen Bilgiler</h1>


    <table class="table table-striped ">
        <thead>
            <tr>
                <th scope="col">TC.</th>
                <th scope="col">Tel</th>
                <th scope="col">Esas No</th>
                <th scope="col">Karar No</th>
                <th scope="col">Ad / Soyad</th>
                <th scope="col">Yakınlık Derecesi</th>
                <th scope="col">Dosya</th>
                <th scope="col">Güncelle</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <th scope="row">34798612886</th>
                <td>05322001146</td>
                <td>39204</td>
                <td>234242</td>
                <td>Süha Uzun</td>
                <td>Oğlu</td>
                <td>İndir</td>
                <td><a href="" data-toggle="modal" data-target="#citizenupdate" data-dismiss="modal">Güncelle</a></td>
            </tr>
            <tr>
                <th scope="row">34798612886</th>
                <td>05322001146</td>
                <td>39204</td>
                <td>234242</td>
                <td>Süha Uzun</td>
                <td>Oğlu</td>
                <td>İndir</td>
                <td><a href="" data-toggle="modal" data-target="#citizenupdate" data-dismiss="modal">Güncelle</a></td>
            </tr>
            <tr>
                <th scope="row">34798612886</th>
                <td>05322001146</td>
                <td>39204</td>
                <td>234242</td>
                <td>Süha Uzun</td>
                <td>Oğlu</td>
                <td>İndir</td>
                <td><a href="" data-toggle="modal" data-target="#citizenupdate" data-dismiss="modal">Güncelle</a></td>
            </tr>
        </tbody>
    </table>



</div>

<div class="clearfix">...</div>

ReddiMiras/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



    <div class="col-md-6 align-self-center offset-md-3 video-area">
        <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
            <li class="nav-item">
                <a class="nav-link active" id="pills-home-tab" data-toggle="pill" href="#pills-home" role="tab" aria-controls="pills-home" aria-selected="true">Reddi Miras Sorgulama</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" id="pills-profile-tab" data-toggle="pill" href="#pills-profile" role="tab" aria-controls="pills-profile" aria-selected="false">Vatandaş Girişi Nasıl Olmalı</a>
            </li>
        </ul>
        <div class="tab-content" id="pills-tabContent">
            <div class="tab-pane fade show active information-video" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab"><iframe style="width: 100%; height: 100%;  " src="https://www.youtube.com/embed/9b81mWYIyTo" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
            <div class="tab-pane fade" id="pills-profile" role="tabpanel" aria-labelledby="pills-profile-tab">...</div>
        </div>
    </div>

ReddiMiras/Views/Home/Kvkk.cshtml
@{
    ViewData["Title"] = "Kvkk";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

    <div class="col-md-6 align-self-center offset-md-3 content">
        <h1>KVKK Metni</h1>
        <div class="content-text">
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis iaculis cursus mauris, a vulputate nunc blandit varius. Vestibulum euismod sapien ac enim commodo, sed semper dui molestie. Aliquam non vulputate sapien. Donec vitae nulla dapibus sem luctus facilisis vel at quam. Vestibulum dignissim libero et eros rutrum consectetur. Nullam dui mauris, lobortis quis ipsum quis, mattis facilisis ligula. Mauris tincidunt nunc mollis, pulvinar ligula ac, sodales arcu. Nam ut fermentum ante. Proin condimentum lectus ex, pulvinar suscipit magna egestas quis. In accumsan lectus at eros rutrum iaculis. Suspendisse accumsan, lorem non auctor scelerisque, enim dolor facilisis nisi, a faucibus ligula lacus quis neque. In laoreet lorem magna, ullamcorper ornare erat viverra interdum. Etiam in odio nisi.</p>
            <p>Donec elementum libero in volutpat dapibus. Quisque vel quam nec orci sodales tincidunt sit amet sed sapien. Etiam sagittis dictum pretium. Integer eget convallis nibh. Quisque at blandit nunc. Sed tellus neque, aliquet non libero in, pharetra dignissim neque. Sed eu ante odio. Fusce tincidunt risus eros, laoreet consequat metus pulvinar eget. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Quisque convallis nibh eu faucibus maximus. In nec magna id risus semper dictum vitae vitae nunc. In vehicula leo ac ligula feugiat porta. Nunc tempor nec velit sit amet rhoncus.</p>
            <p>Aenean euismod porta tortor sed luctus. Integer ut mollis magna, a convallis nibh. Integer semper mauris et justo rutrum, in sodales erat efficitur. Donec libero nibh, consequat at porta eu, hendrerit nec enim. Aenean sit amet sollicitudin urna. Morbi eu malesuada dolor, at semper metus. Nullam lacus arcu, cursus at lobortis eu, facilisis at arcu.</p>
        </div>
    </div>

ReddiMiras/Views/MyAccount/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_QueryPage.cshtml";
}

<style>

    body {
        background-image: none !important;
    }

    footer {
        bottom: auto;
    }

    .detail-content {
        height: auto;
        min-height: 700px;
    }
</style>
<div class="breadcrumb">
    <div class="container">
        <div class="text-right">
            <h1>Türkoğlu Avukatlık Bürosu</h1>
            <h2>TC SORGULAMA EKRANI</h2>

            <h3>Hesabınızda</h3>
            <p>55 Kontür / 55 Sorgulama Bulunmaktadır.</p>
        </div>
    </div>
</div>

<div class="container detail-content">
    <div class="row">
        @await Component.InvokeAsync("LeftNav")
        <div class="col-lg-8 col-md-12">
            <h1>Hesabım</h1>

            <form>
                <div class="form-group">
                    <label>Şirket Adı</label>
                    <input type="corporatename" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Gürgen Hukuk Bürosu">
                </div>
                <div class="form-group">
                    <label>Fatura Adresi</label>
                    <input type="invoicename" class="form-control" id="exampleInputPassword1" placeholder="Cevherli Mahallesi, altıpınar sokak, no 16, kat2 daire 3 - Bahçelievler / İstanbul">
                </div>
                <div class="form-group">
                    <label>Vergi Kimlik Numarası</label>
                    <input type="taxidnumber" class="form-control" id="exampleInputPassword1" placeholder="23054350660">
                </div>
                <div class="form-group">
                    <label>Vergi Dairesi</label>
                    <input type="taxname" class="form-control" id="exampleInputPassword1" placeholder="Kocasinan V.D.">
                </div>
                <div class="form-group">
                    <label>Telefon Numarası</label>
                    <input type="phonenumber" class="form-control" id="exampleInputPassword1" placeholder="0 212 200 22 22">
                </div>
                <div class="form-group">
                    <label>Cep Numarası</label>
                    <input type="mobilenumber" class="form-control" id="exampleInputPassword1" placeholder="0 532 200 22 22">
                </div>
                <button type="submit" class="btn btn-success" data-dismiss="modal">Güncelle</button>
            </form>

        </div>
    </div>
</div>

<div class="clearfix">...</div>

@await Component.InvokeAsync("Footer")
@await Component.InvokeAsync("Inquiry")
@await Component.InvokeAsync("Citizen")

ReddiMiras/Views/PastQueries/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_QueryPage.cshtml";
}

<style>

    body {
        background-image: none !important;
    }

    footer {
        bottom: auto;
    }

    .detail-content {
        height: auto;
        min-height: 700px;
    }
</style>
<div class="breadcrumb">
    <div class="container">
        <div class="text-right">
            <h1>Türkoğlu Avukatlık Bürosu</h1>
            <h2>TC SORGULAMA EKRANI</h2>

            <h3>Hesabınızda</h3>
            <p>55 Kontür / 55 Sorgulama Bulunmaktadır.</p>
        </div>
    </div>
</div>

<div class="container detail-content">
    <div class="row">
        @await Component.InvokeAsync("LeftNav")
        <div class="col-lg-8 col-md-12">
            <h1>Daha Önce Sorgulanan TC. ler</h1>
            <form class="form-inline row">
                <div class="form-group mb-2  col-10">
                    <input type="text" class="form-control col-12" id="" placeholder="TC. Kimlik Numarası Gir">
                </div>
                <button type="submit" class="btn btn-primary mb-2">Ara</button>
            </form>
            <div class="responsive-table">
                <table class="table table-striped ">
                    <thead>
                        <tr>
                            <th scope="col">TC.</th>
                            <th scope="col">Tel</th>
                            <th scope="col">Esas No</th>
                            <th scope="col">Karar No</th>
                            <th scope="col">Ad / Soyad</th>
                            <th scope="col">Dosya</th>
                            <th scope="col">Detay Gör</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <th scope="row">34798612886</th>
                            <td>05322001146</td>
                            <td>39204</td>
                            <td>234242</td>
                            <td>Süha Uzun</td>
                            <td>İndir</td>
                            <td><a href="/gecmissorgulardetay">Detay</a></td>
                        </tr>
                        <tr>
                            <th scope="row">34798612886</th>
                            <td>05322001146</td>
                            <td>39204</td>
                            <td>234242</td>
                            <td>Süha Uzun</td>
                            <td>İndir</td>
                            <td><a href="/gecmissorgulardetay">Detay</a></td>
                        </tr>
                        <tr>
                            <th scope="row">34798612886</th>
                            <td>05322001146</td>
                            <td>39204</td>
                            <td>234242</td>
                            <td>Süha Uzun</td>
                            <td>İndir</td>
                            <td><a href="/gecmissorgulardetay">Detay</a></td>
                        </tr>
                    </tbody>
                </table>
            </div>


        </div>
    </div>
</div>

<div class="clearfix">...</div>

@await Component.InvokeAsync("Footer")
@await Component.InvokeAsync("Inquiry")
@await Component.InvokeAsync("Citizen")